apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: groq-speech-ui
  annotations:
    run.googleapis.com/ingress: all
    run.googleapis.com/execution-environment: gen2
spec:
  template:
    metadata:
      annotations:
        run.googleapis.com/execution-environment: gen2
        autoscaling.knative.dev/maxScale: "10"
        autoscaling.knative.dev/minScale: "0"
    spec:
      containerConcurrency: 100
      timeoutSeconds: 60
      containers:
      - name: groq-speech-ui
        image: gcr.io/PROJECT_ID/groq-speech-ui:latest
        ports:
        - name: http1
          containerPort: 3000
        env:
        # API connection (replace with your actual API URL)
        - name: NEXT_PUBLIC_API_URL
          value: "https://groq-speech-api-XXXXX-uc.a.run.app"
        - name: NEXT_PUBLIC_FRONTEND_URL
          value: "https://groq-speech-ui-XXXXX-uc.a.run.app"
        # Debugging (optional)
        - name: NEXT_PUBLIC_VERBOSE
          value: "false"
        - name: NEXT_PUBLIC_DEBUG
          value: "false"
        # Next.js configuration
        - name: NODE_ENV
          value: "production"
        - name: NEXT_TELEMETRY_DISABLED
          value: "1"
        resources:
          limits:
            cpu: "1"
            memory: "1Gi"
          requests:
            cpu: "0.5"
            memory: "512Mi"
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
