version: '3.8'

services:
  groq-speech-api:
    build:
      context: ../../
      dockerfile: deployment/docker/Dockerfile.gpu
    ports:
      - "8000:8000"
    environment:
      - GROQ_API_KEY=${GROQ_API_KEY}
      - HF_TOKEN=${HF_TOKEN}
      - CUDA_VISIBLE_DEVICES=0
    volumes:
      - ../../groq_speech:/app/groq_speech
      - ../../api:/app/api
      - ../../examples:/app/examples
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  groq-speech-ui:
    build:
      context: ../../examples/groq-speech-ui
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
    depends_on:
      - groq-speech-api
    restart: unless-stopped
