version: '3.8'

services:
  # Development API Server (FastAPI) - For groq-speech-ui
  groq-speech-api:
    build:
      context: ../..
      dockerfile: deployment/docker/Dockerfile.dev
    container_name: groq-speech-api-dev
    ports:
      - "8000:8000"
    environment:
      - GROQ_API_KEY=${GROQ_API_KEY}
      - GROQ_API_BASE_URL=${GROQ_API_BASE_URL:-https://api.groq.com/openai/v1}
      - LOG_LEVEL=DEBUG
      - ENVIRONMENT=development
    volumes:
      - ../../:/app
      - ../../logs:/app/logs
      - ../../temp:/app/temp
      - ../../uploads:/app/uploads
    networks:
      - groq-speech-dev-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s

networks:
  groq-speech-dev-network:
    driver: bridge
